### ISSUE TITLE
Revise network message-passing protocol for inter-language implementations

### ISSUE THREAD

**Issue by superdan-t** [BinghamtonRover/Protobuf#1]

**Comment by superdan-t** [comment]
Ways of identifying message type without the hacky C++ struct wrapper/runtime registration trick from last year:
* Protobuf message descriptor full name (string). Protobuf can provide the full name (message name + package) in string form, which can be used to identify the message's type. Very easy, reliable, few limitations. The only con is that mapping a received message to its handler will require string comparison. Messages need to be handled with low latency on Raspberry Pi and desktop. Test whether string comparison vs direct mapping even makes a measurable difference on these platforms.
* Protobuf message descriptor index. Protobuf provides the index of a message in the package. This adds the limitation that all messages must be defined in the same proto package/file, but an integer index allows a direct-mapped table of message type to handler.
* Manually specifying message types using a Protobuf enum. Documenting this method since it was our original plan. It is like the message descriptor index, but worse.

**Comment by Levi-Lesches** [comment]
From our last discussion and https://github.com/BinghamtonRover/rover-control-dashboard/issues/8, it seems: 
- Move all `.proto` files from [`BurtOS-2/src/network/rover_system_messages`](https://github.com/BinghamtonRover/BurtOS-2/tree/main/src/network/rover_system_messages) to this repo
- Add a wrapper `.proto` file that can wrap another message (as a string) and its ID (also a string)
- Include this repo as a submodule in the [dashboard](https://github.com/BinghamtonRover/rover-control-dashboard) and rover-side (?) repositories to generate code
- Implement networking code on both sides that pass around instances of the wrapper message

As an aside -- where is the networking code that'll be running on the rover? There's CAN, of course, but what will unpack the Protobuf messages and pack them into CAN frames? Is that C++ or Python for the Raspberry Pis?

**Comment by Levi-Lesches** [comment]
Done. The `Protobuf` repository (here) has a new `wrapper.proto` file and the `Dashboard` and `Subsystems-Computer` repositories can include this repository as a submodule.
